name: cryptostream
version: "0.1.0"
profile: cryptostream

config-version: 2

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
test-paths: ["tests"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  cryptostream:
    staging:
      +materialized: table
      +schema: silver
    marts:
      +materialized: table
      +schema: gold